[bmscriptsbox]

[bmscriptsbox.info]
id = "a008d9f5-9991-4fd1-bf05-8d0afb95f2d0"
name = "复制文件路径"
desc = "文件路径批量提取脚本，支持配置引号、路径分隔符、换行符、排序方式等。通过不忙脚本盒子的右键触发功能，可实现鼠标选中文件，批量提取文件路径到系统剪贴板"
version = "1.0.1"
icon = "./imgs/logo.png"

[bmscriptsbox.runtime]
language = "autohotkey"
language_version = ">=2.0.0"
entry = "main.ahk"
terminal = "never"

[bmscriptsbox.triggers.context_menu]
enabled = true
targets = ["files", "directory"]

[bmscriptsbox.triggers.shortcut]
enabled = true
input_type = "items"

[[bmscriptsbox.inputs]]
name = "target_paths"
type = "list"
description = "需要提取文件路径的文件路径"
